# Generated by Django 4.2.4 on 2023-08-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_remove_bookmark_url_bookmark_site_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='site_url',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='url',
            field=models.URLField(default=1, verbose_name='Site URL'),
            preserve_default=False,
        ),
    ]
